import React from "react";
import Image from "next/image";
import Link from "next/link";
import { db } from "@/configs/db";
import { CourseList } from "@/configs/schema";
import { desc } from "drizzle-orm";
import { Button } from "@/components/ui/button";
import { RiCompassDiscoverLine, RiUserLine } from "react-icons/ri";

export const dynamic = "force-dynamic";

export default async function Explore() {
  let courses: any[] = [];
  try {
    // Fetch latest 12 courses generated on the platform
    courses = await db
      .select()
      .from(CourseList)
      .orderBy(desc(CourseList.id))
      .limit(12);
  } catch (e) {
    console.error("Failed to query explore courses:", e);
  }

  const getCategoryImage = (category: string) => {
    const cat = category.toLowerCase();
    if (cat.includes("program") || cat.includes("code") || cat.includes("dev")) return "/programming-logo.jpg";
    if (cat.includes("data science") || cat.includes("analytics")) return "/Data-science-logo.jpg";
    if (cat.includes("ai") || cat.includes("machine") || cat.includes("ml")) return "/aiml-logo.jpg";
    if (cat.includes("cyber") || cat.includes("security")) return "/cybersecurity-logo.jpg";
    if (cat.includes("music") || cat.includes("art")) return "/Music-logo.jpg";
    if (cat.includes("game") || cat.includes("gaming")) return "/game-logo.jpg";
    return "/aiml-logo.jpg";
  };

  const getCourseDesc = (courseOutput: any) => {
    if (typeof courseOutput === "string") {
      try {
        return JSON.parse(courseOutput)?.description;
      } catch (e) {
        return "";
      }
    }
    return courseOutput?.description;
  };

  return (
    <div className="max-w-5xl mx-auto space-y-8 pb-12 text-gray-900 dark:text-white">
      
      {/* Title Header */}
      <div className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-3xl p-8 shadow-xs flex flex-col md:flex-row items-center justify-between gap-6 transition-colors duration-200">
        <div>
          <h2 className="text-2xl md:text-3xl font-extrabold text-gray-900 dark:text-white flex items-center gap-2">
            <RiCompassDiscoverLine className="text-pink-600 animate-spin-slow" /> Explore AI Courses
          </h2>
          <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
            Browse custom-tailored courses generated by our creative community of learners.
          </p>
        </div>
        <Link href="/create-course">
          <Button className="bg-black dark:bg-white dark:text-black dark:hover:bg-gray-100 text-white hover:bg-gray-900 font-bold px-6 py-5 rounded-xl text-xs">
            + Generate Yours
          </Button>
        </Link>
      </div>
 
      {/* Grid of latest courses */}
      {courses.length === 0 ? (
        <div className="text-center py-20 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-3xl p-8 transition-colors duration-200">
          <p className="text-gray-500 dark:text-gray-400 text-sm">No public courses have been generated yet.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {courses.map((course) => (
            <div
              key={course.id}
              className="flex flex-col bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl shadow-sm hover:shadow-md transition-all duration-300 overflow-hidden group"
            >
              {/* Cover Photo */}
              <div className="relative w-full h-36 bg-gray-150 dark:bg-gray-800 overflow-hidden">
                <Image
                  src={getCategoryImage(course.category)}
                  alt={course.name}
                  fill
                  className="object-cover group-hover:scale-105 transition-transform duration-300"
                />
                <div className="absolute top-3 left-3 bg-white/95 dark:bg-gray-900/90 backdrop-blur-xs px-2.5 py-1 rounded-full text-[10px] font-bold text-gray-800 dark:text-gray-200 shadow-2xs">
                  {course.category}
                </div>
              </div>
 
              {/* Course details */}
              <div className="flex flex-col flex-1 p-5 justify-between">
                <div>
                  <h4 className="text-base font-bold text-gray-900 dark:text-white line-clamp-1 group-hover:text-pink-600 dark:group-hover:text-pink-400 transition-colors">
                    {course.name}
                  </h4>
                  <p className="text-xs text-gray-500 dark:text-gray-400 mt-1 line-clamp-2 leading-relaxed">
                    {getCourseDesc(course.courseOutput) || "Custom course covering essential topic syllabus concepts."}
                  </p>
                </div>
 
                <div className="mt-5 space-y-4 pt-4 border-t border-gray-100 dark:border-gray-850">
                  {/* Badges */}
                  <div className="flex flex-wrap gap-1.5">
                    <span className="bg-pink-50 dark:bg-pink-950/45 text-pink-700 dark:text-pink-300 text-[9px] font-bold px-2 py-0.5 rounded-md uppercase">
                      {course.level}
                    </span>
                    <span className="bg-blue-50 dark:bg-blue-950/45 text-blue-700 dark:text-blue-300 text-[9px] font-bold px-2 py-0.5 rounded-md">
                      {course.language}
                    </span>
                  </div>
 
                  {/* Creator name and action */}
                  <div className="flex items-center justify-between gap-3 text-[10px] text-gray-500 dark:text-gray-450">
                    <span className="flex items-center gap-1 font-medium truncate max-w-[120px] text-gray-700 dark:text-gray-300">
                      <RiUserLine className="shrink-0" /> {course.username || "Anonymous"}
                    </span>
                    
                    <Link href={`/course/${course.courseid}`}>
                      <Button
                        variant="outline"
                        className="border-gray-300 dark:border-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 text-[10px] py-1.5 px-3 h-auto rounded-lg"
                      >
                        Learn Now
                      </Button>
                    </Link>
                  </div>
                </div>
 
              </div>
 
            </div>
          ))}
        </div>
      )}
 
    </div>
  );
}